spring.application.name=jrvs-trading

spring.datasource.url=${PSQL_URL}
spring.datasource.username=${PSQL_USER}
spring.datasource.password=${PSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

finnhub_token=${FINNHUB_TOKEN}
finnhub_host=https://finnhub.io/api/v1/quote
finage_host=https://api.finage.co.uk/last/stock/
finage_token=${FINAGE_TOKEN}
server.port=5000
