package ca.jrvs.apps.trading.service;

import ca.jrvs.apps.trading.Model.Account;
import ca.jrvs.apps.trading.Model.SecurityOrder;
import ca.jrvs.apps.trading.Model.Trader;
import ca.jrvs.apps.trading.dao.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class TraderService {

  @Autowired
  TraderDao traderDao;

  @Autowired
  AccountJpaRepository accountDao;

  @Autowired
  SecurityOrderDao securityDao;

  /**
   * Create a new trader and initialize a new account with 0 amount
   * - validate user input (all fields must be non empty)
   * - create a trader
   * - create an account
   * - create, setup, and return a new traderAccountView
   *
   * Assumption: to simplify the logic, each trader has only one account where traderId == accountId
   *
   * @param trader cannot be null. All fields cannot be null except for id (auto-generated by db)
   * @return traderAccountView
   * @throws IllegalArgumentException if a trader has null fields or id is not null
   */

  public TraderAccountView createTraderAndAccount(Trader trader) {
    if (trader == null) {
      throw new IllegalArgumentException("Trader cannot be null");
    }
    if (trader.getId() != null) {
      throw new IllegalArgumentException("Trader ID must be null for new traders");
    }
    if (trader.getFirst_name() == null || trader.getFirst_name().isBlank()) {
      throw new IllegalArgumentException("Trader first name cannot be null or empty");
    }
    if (trader.getLast_name() == null || trader.getLast_name().isBlank()) {
      throw new IllegalArgumentException("Trader last name cannot be null or empty");
    }
    if (trader.getEmail() == null || trader.getEmail().isBlank()) {
      throw new IllegalArgumentException("Trader email cannot be null or empty");
    }

    Trader savedTrader = traderDao.save(trader);

    Account account = new Account();
    account.setTrader(trader);
    account.setAmount(0.0);

    Account savedAccount = accountDao.save(account);

    // Build and return the TraderAccountView
    TraderAccountView traderAccountView = new TraderAccountView();
    traderAccountView.setTrader(savedTrader);
    traderAccountView.setAccount(savedAccount);

    return traderAccountView;
  }

  /**
   * A trader can be deleted if and only if it has no open position and 0 cash balance
   * - validate traderId
   * - get trader account by traderId and check account balance
   * - get positions by accountId and check positions
   * - delete all securityOrders, account, trader (in this order)
   *
   * @param traderId must not be null
   * @throws IllegalArgumentException if traderId is null or not found or unable to delete
   */
  public void deleteTraderById(Integer traderId) {
    Trader trader;
    try {
      trader = traderDao.findById(traderId).get();

    } catch (Exception e) {
      throw new IllegalArgumentException("Given ID not found");
    }
    Account account = accountDao.getAccountByTraderId(traderId);
    if (account.getAmount() == 0.0){
      List<SecurityOrder> orders = securityDao.findByAccount_id(account.getId());
      if (!orders.isEmpty()) {
        securityDao.deleteAll(orders);
      }
      accountDao.delete(account);
      traderDao.delete(trader);
    }
    else {
      throw new IllegalArgumentException("Account Amount not 0");
    }

  }

  /**
   * Deposit a fund to an account by traderId
   * - validate user input
   * - find account by trader id
   * - update the amount accordingly
   *
   * @param traderId must not be null
   * @param fund must be greater than 0
   * @return updated Account
   * @throws IllegalArgumentException if traderId is null or not found,
   * 									and fund is less than or equal to 0
   */
  public Account deposit(Integer traderId, Double fund) {
    Trader trader;
    try {
      trader = traderDao.findById(traderId).get();

    } catch (Exception e) {
      throw new IllegalArgumentException("Given ID not found");
    }
    Account account = accountDao.getAccountByTraderId(traderId);

    Double new_sum = account.getAmount() + fund;
    account.setAmount(new_sum);
    accountDao.save(account);
    return account;
  }

  /**
   * Withdraw a fund to an account by traderId
   * - validate user input
   * - find account by trader id
   * - update the amount accordingly
   *
   * @param traderId must not be null
   * @param fund must be greater than 0
   * @return updated Account
   * @throws IllegalArgumentException if traderId is null or not found,
   * 									and fund is less than or equal to 0
   */
  public Account withdraw(Integer traderId, Double fund) {
    Trader trader;
    try {
      trader = traderDao.findById(traderId).get();

    } catch (Exception e) {
      throw new IllegalArgumentException("Given ID not found");
    }
    Account account = accountDao.getAccountByTraderId(traderId);

    Double new_sum = account.getAmount() - fund;
    if (new_sum < 0.0) {
      throw new IllegalArgumentException("Not Enough Fund");
    }
    account.setAmount(new_sum);
    accountDao.save(account);
    return account;  }
}
